server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

eureka:
  client:
    enabled: true

stats-server:
  service-id: stats-server
  app: ewm-main-service

grpc:
  client:
    collector:
      address: discovery://collector
      negotiation-type: plaintext
    analyzer:
      address: discovery://analyzer
      negotiation-type: plaintext
