CREATE TABLE IF NOT EXISTS event_similarities (
    first_event  BIGINT,
    second_event BIGINT,
    score        DOUBLE PRECISION,
    PRIMARY KEY (first_event, second_event)
);

CREATE TABLE IF NOT EXISTS user_actions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    event_id         BIGINT NOT NULL,
    user_score       DOUBLE PRECISION NOT NULL,
    timestamp_action TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_user_event UNIQUE (user_id, event_id)
);
